### PR TITLE
MDCCloseable instead of Closeable to avoid throwing of IOException

### PR DESCRIPTION
**Pull request by twillouer**
Avoid throwing IOException in putCloseable...

### CODE REVIEW

**Comment by denisa** [comment]
Please consider merging this. Having to code for IOException nullifies the advantage of putCloseble()…

**Comment by mattbishop** [comment]
@denisa where is the IOException thrown? I'm not fond of the IllegalArgumentException (NPEs are fine for null values) but I am not seeing the IOE.

**Comment by ceki** [comment]
Makes sense to me as the ```MDCClose.close``` method will never throw an exception.

**Comment by twillouer** [comment]
Yes, sorry @ceki, bad design in the first PR.

In this PR, MDCCloseable.close never send exception.

**Pull request merged**
