### PR TITLE
Binding Ambiguity check skipped for Andriod

### PR DESCRIPTION
**Pull request by jeffreyzh**
As Dex cant by design have duplicate class, there would never be a 'Binding Ambiguity'.

1. LoggerFactory.getLogger is mostly called via MainActivity. Which gives a black screen before the first activity loads.
2. This operation takes 200-600 Inclusive CPU Time as per DDMS.

This fix get Incl CPU Time to sub 10

### CODE REVIEW

**Comment by ceki** [comment]
@jeffreyzh Since 1.7.14, the binding ambiguity check is skipped the during initialization under Android in order to improve performance. What's going on?

**Comment by jeffreyzh** [comment]
I update the version to 1.7.4 ，the following method takes a long time during initialization
```
loggerFactoryClassLoader.getResources(STATIC_LOGGER_BINDER_PATH)
```
the but I found the findPossibleStaticLoggerBinderPathSet is not skipped

**Comment by ceki** [comment]
@jeffreyzh My apoligies, Problem fixed in https://github.com/qos-ch/slf4j/commit/5a95202d93c6994d
The fix will be part of version 1.7.17 to be released shortly.

**Comment by jeffreyzh** [comment]
Well done，thank you so much.

**Pull request closed without merging**
