### PR TITLE
fix typo getRequesteApiVersion -> getRequestedApiVersion

### PR DESCRIPTION
**Pull request by osiegmar**

### CODE REVIEW

**Comment by osiegmar** [comment]
CI seem to be broken -- wasn't me :)

**Comment by damjad** [comment]
It's because Travis is unable to find JDK 6 or JDK 6 is not configured in _.m2/toolchains.xml_ file.

**Comment by dp-rufus** [comment]
cc @ceki this needs to be fixed before 2.0 leaves alpha

**Comment by rufoa** [comment]
cc @ceki this needs to be fixed before 2.0.0 leaves alpha

**Comment by ceki** [comment]
Resolved in [https://github.com/qos-ch/slf4j/commit/3e2381ea694c|commit 3e238].

See also [https://jira.qos.ch/browse/SLF4J-516|SLF4J-516]

**Comment by rufoa** [comment]
thanks!

**Comment by osiegmar** [comment]
PR outdated and fixed

**Pull request closed without merging**
