### PR TITLE
SLF4J-309 Adding getAdditivity() method to log4j Category with same signature

### PR DESCRIPTION
**Pull request by dimitrisli**
SLF4J-309 Adding getAdditivity() method to log4j Category with same signature

### CODE REVIEW

**Comment by mattbishop** [comment]
This method exists and is public in Log4J's Category: https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Category.html#getAdditivity()

**Comment by ceki** [comment]
Why is commit 27e3eeaed3182be17bde1768fc1b09de025388aa from slf4j-scala-api (a module a different project) part of this pull request? @mattbishop, why was it merged? 

The diff for 27e3eeaed3182be17bde1768fc1b09de025388aa  is 36278 lines long. It needs to be reverted which I will do promptly once I figure out the appropriate git command.

**Comment by mattbishop** [comment]
The massive #1 came in with this PR but it did not show up in the PR review itself. If you look at the "Files changed" tab above, only @dimitrisli change is in the diff. I saw the update to merge #1 but thought it was already merged into master as those changes did not show up in the change list.

**Comment by ceki** [comment]
@mattbishop OK, I see that "changed files" tab only shows a single file. I wonder if "squashing" would have been appropriate here. I think https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request may provide useful some information though I have not read it yet.

**Comment by ceki** [comment]
@dimitrisli, as I am trying to back trace this PR, may I ask you to explain how 27e3eeaed3182be17bde1768fc1b09de025388aa end up in this PR? I presume that you did _not_ rebase but merged your mattbishop/slf4j repository on the latest qos_ch/slf4j repository? Am I assuming correctly?

**Comment by dimitrisli** [comment]
@ceki @mattbishop , apologies for the confusion. 

27e3eea is the product of the following actions (all via github site): 

1) I had a fork created a few weeks prior to the v1.7.11 release. 
2) I've clicked on 'Pull Requests' tab. 
3) I've clicked on 'New Pull Request' button. 
4) I've clicked on 'switching the base'. 
5) Then all the contents of 27e3eea appeared representing all the updates since a bit prior the v.1.7.11 release. 
6) I've clicked 'Send Pull Request'. I believe that's the reason this is visible. 
7) I've finally clicked 'Merge Pull Request' and 'Confirm Merge'.

Then I've cloned locally and applied the changes via IntelliJ and used its GitHub integration thereafter.

If this is causing any issues or doubts please revert or cancel it. I have to admit I have to work on my Git skills.

**Comment by ceki** [comment]
Thank you for detailing the steps. I guess that github does a merge instead of rebase under the covers. I'll try to ascertain this statement by reading up on the documentation.

BTW, here is a useful reference for nifty git commands http://git-man-page-generator.lokaltog.net/ :-).

**Pull request merged**
