### PR TITLE
Update comments to point to JIRA equivalents of old Bugzilla bugs

### PR DESCRIPTION
**Pull request by jmthibault79**

### CODE REVIEW

**Comment by mattbishop** [comment]
rebase?

**Comment by jmthibault79** [comment]
Rebased.

**Comment by mattbishop** [comment]
Build is failing on Travis.

**Comment by jmthibault79** [comment]
Fixed: a test was dependent on its own line numbers, so it needed an update after I added a comment line.

**Comment by mattbishop** [comment]
Actually why are we keeping bug references in the code at all?

**Comment by jmthibault79** [comment]
I was able to solve a problem I had with using SLF4J thanks to one of these bug comments - once I was able to map its Bugzilla URL to the new JIRA ticket.

That's my motivation, anyway.

**Comment by ceki** [comment]
@mattbishop Comments in the code mention a bugzilla/JIRA issues for further details on the context of the problem. The line number issue is quite different. The test in question verifies line number extraction and hence depends on the caller's line number. It's quite fragile but the fix is also quite easy.

@jmthibault79  As bugzilla.slf4j.org is no longer available, this patch was highly welcome. Many thanks.

**Pull request merged**
