### PR TITLE
BasicMDCAdapter: use cached value of isJDK14()

### PR DESCRIPTION
**Pull request by panchenko**

### CODE REVIEW

**Comment by mattbishop** [comment]
Do you have any perf metrics to show this is an improvement? Usually the JIT will optimize these kinds of calls at runtime if the test always returns the same answer with the same data.

**Comment by panchenko** [comment]
a) That looks lie an initial not finished idea, as that variable is not used at the moment
b) I don't think JIT can optimize this function call - that expression can't be simplified to a constant

**Comment by SvenBunge** [comment]
Please correct me but I think JDK1.4 isn't supported anymore since 1.7. I've removed the JDK1.4-case completly in my PR #119 
See http://www.slf4j.org/faq.html#requirements

**Comment by panchenko** [comment]
Makes sense.

**Pull request closed without merging**
