### PR TITLE
this module is Apache 2.0 licensed

### PR DESCRIPTION
**Pull request by hboutemy**
having a pom.xml in sync may help consumers

### CODE REVIEW

**Comment by ceki** [comment]
Thanks Hervé.

**Comment by eolivelli** [comment]
@ceki
Can you cherry pick to 1.7 line?
We need it for Maven binary.
I am also gently asking for a release of 1.7.x

**Comment by ceki** [comment]
I am on it. Perhaps I should mention that deploying on Maven Central is quite slow.

**Comment by eolivelli** [comment]
Thank you @ceki 

"Maven Central is quite slow."
it is due to the provider that is hosting Maven central, as far as I know they are working hard to make the system run well again

**Comment by ceki** [comment]
@eolivelli  Done. 1.7.29 should be available in MavenCentral. By the way, deployoing to MavenCentral  was actually not that bad.

**Comment by eolivelli** [comment]
@ceki 
it looks like 1.7.29 is still not available, did you have problems ?
https://mvnrepository.com/artifact/org.slf4j/jcl-over-slf4j

**Comment by ceki** [comment]
I see it here: http://repo2.maven.org/maven2/org/slf4j/slf4j-api/1.7.29/

**Comment by eolivelli** [comment]
Actually I am able to compile with 1.7.29.
Maybe it is a problem of Maven Search Engine.

Thank you so much!
Have a nice weekend

**Comment by ceki** [comment]
You too.

**Comment by eolivelli** [comment]
@ceki isn't slf4-api Apache License 2.0 as well ? I see it is MIT

https://github.com/qos-ch/slf4j/blob/master/pom.xml

the link to the license is to a php page 
Maybe it is better to make it point to a plain txt file
https://raw.githubusercontent.com/qos-ch/slf4j/master/LICENSE.txt

**Comment by hboutemy** [comment]
> Maybe it is a problem of Maven Search Engine.
not really a problem, but a delay between the artifact availability for download (= what build tool uses) and the misc indexes for search engines

**Comment by ceki** [comment]
slf4j is MIT licensed with the exception of jcl-over-slf4j.

**Comment by eolivelli** [comment]
@ceki see
https://github.com/qos-ch/slf4j/blob/4a1d5194fe63e503959cffb0ba05be0cb26e0eab/pom.xml#L25

**Comment by ppkarwasz** [comment]
> slf4j is MIT licensed with the exception of jcl-over-slf4j.

`log4j-over-slf4j` seems also to be licensed under `Apache-2.0`, is this right?

**Pull request merged**
