### PR TITLE
Added option to load service provider from passed in ClassLoader

### PR DESCRIPTION
**Pull request by m-froehlich**
The LoggerFactory will load service providers from a passed in ClassLoader, if given. Otherwise previous behavior is maintained. The getLogger(Class) method receives a class, that is used to extract a ClassLoader from.

Signed-off-by: Marvin Fröhlich m.froehlich@infolog.de

### CODE REVIEW

**Comment by m-froehlich** [comment]
I have created another patch branch with the same changes, but with Singed-off-by line in the commit message.

What checks haved failed? What do I need to do?

**Comment by ceki** [comment]
This change introduces behavior which is subtly different than older code. It will not be merged.

**Comment by m-froehlich** [comment]
Without my patch slf4j simply doesn't work in combination with a custom class loader.

**Comment by m-froehlich** [comment]
Can you please comment on this? This really is a bug in the code, that needs to be fixed.

Do I have to do anything to make this fix good to be merged?

**Comment by ceki** [comment]
Your patch changes the public API. Moreover, it modifies existing behavior and has a much bigger impact than you seem to think. 

It will not be merged. I can't be clearer than this.

**Comment by m-froehlich** [comment]
Are you open to an API extension on that front, that can be used optionally to workaround this bug? Hopefully the guys at PAC4J will make use of it then.

**Pull request closed without merging**
